@startuml

class Pasient

class ReseptListe

class Resept {
    produktnavn ELLER
    pakning OR
    virkestoffMedStyrke
}

class ReseptBunke {
    forskrivningsdato
    egenandelsperioder
}

class ReseptVarsel {
    interaksjonsvarsel
    nyttLegemiddel
    endretDosering
    høyDosering
    polyfarmasi
    dobbelforskrivning
}

class Legemiddel

class Helseperson

class Reseptutlevering

class ReseptutleveringAksjon {
    kontaktet_lege j/n
    informert pasient j/n
    notat
}

Pasient -down- ReseptListe
ReseptListe -right- "*" Resept
ReseptBunke -up- Helseperson: lege
Resept "*" -up- ReseptBunke
Resept -down- "*" ReseptVarsel
Resept -right- Reseptutlevering
Reseptutlevering -down- ReseptutleveringAksjon
ReseptVarsel -right- ReseptutleveringAksjon

Resept -up- "*" Legemiddel: alternativer
Reseptutlevering -up- Legemiddel
Reseptutlevering -up- Helseperson: farmasøyt

hide empty members
hide methods
@enduml
