@startuml

class Pasient

class ReseptListe

class Resept {
    produktnavn ELLER
    pakning OR
    virkestoffMedStyrke
}

class ReseptBunke {
    forskrivningsdato
    egenandelsperioder
}

class ReseptKurv {
}

class ReseptVarsel {
    interaksjonsvarsel
    nyttLegemiddel
    endretDosering
    høyDosering
    polyfarmasi
    dobbelforskrivning
}

class Legemiddel

class Helseperson

class ReseptUtlevering

class ReseptUtleveringAksjon {
    kontaktet_lege j/n
    informert pasient j/n
    notat
}

Pasient -down- ReseptListe
ReseptListe -right- "*" Resept
ReseptBunke -up- Helseperson: lege
Resept "*" -up- ReseptBunke
Resept -down- "*" ReseptVarsel
Resept -right- ReseptUtlevering
ReseptUtlevering -down- ReseptUtleveringAksjon
ReseptVarsel -right- ReseptUtleveringAksjon

Resept -up- "*" Legemiddel: alternativer
ReseptUtlevering -up- Legemiddel
ReseptKurv -up- Helseperson: farmasøyt

ReseptKurv -down- "*" ReseptUtlevering

hide empty members
hide methods
@enduml
