@startuml

box "Apotek"
    actor Apoteker
    actor Farmasøyt
end box

actor Buypass

box "DIFA"
    participant DifaGUI
    database db
    database HSM
    database Tilgangslogg
end box

participant eHelse

== registrere sertifikat ==
DifaGUI -> Apoteker: Varsel om nytt sertifikatbehov
Buypass -> Apoteker: Sertifikat, nøkkel, passord
Apoteker -> DifaGUI: Registrere sertifikat, passord
activate DifaGUI
DifaGUI -> HSM: Sertifikat
DifaGUI -> db: Sertifikatpassord
Apoteker <-- DifaGUI
deactivate DifaGUI
...

== Bruke sertifikat ==
Farmasøyt -> DifaGUI: Registrer utlevering
activate DifaGUI
DifaGUI -> DifaGUI: Generere M10
DifaGUI -> DifaGUI: Signere M10
activate DifaGUI
DifaGUI -> Tilgangslogg: Logg signeringsaksjon\nmed JWT og IP for bruker
DifaGUI -> db: Hent passord
DifaGUI -> HSM: M10 hash + passord
DifaGUI <-- HSM: Signatur
DifaGUI --> DifaGUI
deactivate DifaGUI
DifaGUI -> eHelse: Signert Utleveringsmelding (M10)
Farmasøyt <-- DifaGUI
deactivate DifaGUI

@enduml
