@startuml

title Inhalasjonsveiledning

actor Apotektekniker
participant POS
participant DIFA
participant HELFO


group Dialog med Kjede POS
Apotektekniker -> POS: Velger Inhalasjonsveiledning
Apotektekniker <-- POS: Redirect
end group
group Dialog med DIFA
Apotektekniker -> DIFA: Vis Personsøk skjema
Apotektekniker -> DIFA: Angi person (fødselsnummer eller navn + fødselsdato)
Apotektekniker <-- DIFA: Vis instrukser for behandlingen
Apotektekniker -> DIFA: Angi informasjon om behandlingen (eks: antall repetisjoner)
Apotektekniker -> DIFA: Fullfør behandling
activate DIFA
DIFA -> DIFA: Journalføre behandling
DIFA -> DIFA: Beregne refusjon og egenandel
DIFA -> HELFO: Refusjonskrav
Apotektekniker <-- DIFA: Redirect med varenummer og egenandel
deactivate DIFA
end group
group Dialog med Kjede POS
Apotektekniker -> POS: Legg til egenandel i handlekurv
Apotektekniker <-> POS: Vis oppgjørsgrunnlag
Apotektekniker <-> POS: Fullfør salg
end group


