@startuml

participant POS
box "Difa tjenesten"
    participant Difa
    database HPR
    database Farmalogg
end box
database Personregisteret
database RF
participant HELFO

activate Difa
POS -> Difa: Find person basert på kriterier
Difa -> Personregisteret
POS <-- Difa: Liste med personer
deactivate Difa

POS -> Difa: Hent resepter for person
activate Difa
Difa -> RF: Hent resepter for person
POS <-- Difa: Reseptliste
deactivate Difa

POS -> Difa: Ekspeder resept
activate Difa
Difa -> RF: Ekspeder resept
Difa -> HPR: Hent rekvisisjonsrett
Difa -> Farmalogg: Medikament-informasjon
Difa <-- Farmalogg: Bivirkninger, interaksjoner, trinnpris,\nbyttegruppe med legemiddeldetaljer
Difa -> Difa: Bruk historikk til å generere varsler
POS <-- Difa: Reseptliste med alternativer,\nbivirkninger, varsler
deactivate Difa

group Valgfrie operasjoner
POS -> Difa: Beregne refusjon basert på varevalg
POS -> Difa: Forfalskningskontroll
end group


POS -> Difa: Registrer utlevering med varevalg, strekkoder,\noppdatert etikett,\nfarmasøyts aksjon for alle varsler,\nunderskrift
Note right of POS: Her kunne Difa tilby en mobil app for farmasøyt for farmasikontroll
activate Difa
Difa -> Difa: Verifiser rekvirent, varsler, strekkoder
Difa -> RF: Utleveringsmelding
Difa -> HELFO: Send refusjonskrav
POS <-- Difa: OK/feilkoder
deactivate Difa



@enduml
