@startuml

actor Pasient
actor Apotektekniker
actor Farmasøyt

node DifaGUI #limegreen
node Regnskap <<kjede>> #lime

node Difa #limegreen

node helsenorge.no #yellow
node HELFO #yellow
node HPR #yellow

Pasient <-> Apotektekniker
Apotektekniker -down-> DifaGUI
Farmasøyt -down-> DifaGUI

DifaGUI -down-> Difa
Regnskap -down-> Difa: Refusjonstatus

Difa -down-> helsenorge.no: Journal
Difa -down-> HELFO: Refusjon
Difa -down-> HPR: Autorisasjon

@enduml
