@startuml

actor ApotekA as "Kjede A"
actor ApotekB as "Kjede B"

node POS #lime
node ERP #lime
node DIFA #limegreen
node RF #pink
node Farmalogg #yellow
node SLV #yellow
node HELFO #yellow
node Nettapotek #lime
node Multidose #lime
node FarmaPro <<bro>> #pink

ApotekA -down-> POS
POS -down-> DIFA
POS -left-> ERP
Nettapotek -down-> DIFA
Multidose -down-> DIFA
ApotekB -down-> FarmaPro
FarmaPro -down-> DIFA
DIFA <-left-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
DIFA <-right- Farmalogg
Farmalogg <-down- SLV: FEST
DIFA <-down-> HELFO: M18, M22, M23


@enduml
