@startuml

actor Pasient
actor Apotektekniker
actor Farmasøyt
actor Lege

node POS #lime
node ERP #lime
node Nettapotek #lime
node Multidose #lime
node Difa #limegreen

node RF #pink
node Farmalogg #yellow
node SLV #yellow
node HELFO #yellow
node HDIR #yellow
node helsenorge.no #yellow

Pasient <-down-> Lege
Lege -right-> EPJ: Resept
EPJ -right-> RF: Resept
Pasient <-right-> Apotektekniker
Apotektekniker -down-> POS
Farmasøyt -down-> POS

POS -down-> Difa
POS -left-> ERP
Nettapotek -down-> Difa
Multidose -down-> Difa
Difa <-left-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
Difa <-right- Farmalogg
Farmalogg <-down- SLV: FEST
Difa <-down-> HELFO: M18, M22, M23
Difa <-down- HDIR: HPR db
Difa -down-> helsenorge.no: Journal


@enduml
