@startuml

title DIFA leser fra kjedenes varesystem (opsjon)

actor Apotekansatt
actor Farmasøyt
box "Kjede"
    participant POS
    participant Varesystem
end box
box "DIFA"
    participant DifaGUI
    participant DIFA
end box

Apotekansatt -> POS: Velger hent resept
Apotekansatt <-- POS: Redirect
group Dialog med DIFA
Apotekansatt -> DifaGUI: Vis Personsøk skjema
Apotekansatt -> DifaGUI: Angi person (fødselsnummer eller navn + fødselsdato)
Apotekansatt <-- DifaGUI: Vis resepter
Apotekansatt -> DifaGUI: Velg resept
activate DifaGUI
DifaGUI-> DIFA: Hent resept 
DIFA -> DIFA: Hent varer i byttegruppe
DIFA -> DIFA: Påfør informasjon og varsler
DifaGUI <-- DIFA
note over Varesystem : Kjeden har ansvar for at varesystem\nimplementere API spesfisert av DIFA
DifaGUI-> Varesystem: <color red>Pris og beholdning for\n<color red>alle aktuelle legemidler\n<color red>for apotek
DifaGUI<-- Varesystem
Apotekansatt <--DifaGUI: Varsler, byttealternativer med priser, beholdning
deactivate DifaGUI
Apotekansatt -> DifaGUI: Velg legemiddel
Apotekansatt <-- DifaGUI: Klargjør reseptetikett, ta opp print-dialog

newpage

note right of Apotekansatt: DIFA GUI åpner nettlesers print-dialog
Apotekansatt -> Apotekansatt: Skriv reseptetikett
Apotekansatt -> DifaGUI: Scan strekkode på etikett og pakning
note right of Apotekansatt: Strekkodescanner i tastaturmodus
DifaGUI -> DIFA: Teknisk kontroll
Apotekansatt -> Farmasøyt: "Kan du gjøre\nfarmasøytkontroll"
Farmasøyt -> DifaGUI: Vis resepter klar til farmasøytkontroll
Farmasøyt -> DifaGUI: Utfør farmasøytkontroll
Apotekansatt <- Farmasøyt: "Vær så god"
Apotekansatt -> DifaGUI: Utlever
Apotekansatt -> POS: Importer reseptkurver
activate POS
POS -> DIFA: <color red>List reseptkurver tilhørende apotekansatt
Apotekansatt <-- POS: Reseptkurvliste
deactivate POS
Apotekansatt -> POS: Plukk en eller flere reseptkurver
activate POS
POS -> DIFA: <color red>Hent reseptkurv
Apotekansatt <-- POS: Vis oppdatert "handlekurv"
deactivate POS
Apotekansatt -> POS: <color red>Registrer signatur og betaling
activate POS
POS -> DIFA: <color red>Fullfør utlevering
Apotekansatt <-- POS
deactivate POS

@enduml
