@startuml

actor Apotektekniker
actor Farmasøyt
box "DIFA tjenesten"
    participant DIFA
    database HPR
    database Farmalogg
end box
database Personregisteret
database RF
participant HELFO

activate DIFA
Apotektekniker -> DIFA: Find person basert på kriterier
DIFA -> Personregisteret
Apotektekniker <-- DIFA: Liste med personer
deactivate DIFA

Apotektekniker -> DIFA: Hent resepter for person
activate DIFA
DIFA -> RF: Hent resepter for person
Apotektekniker <-- DIFA: Reseptliste
deactivate DIFA

Apotektekniker -> DIFA: Ekspeder resept
activate DIFA
DIFA -> RF: Ekspeder resept
DIFA -> HPR: Hent rekvisisjonsrett
DIFA -> Farmalogg: Medikament-informasjon
DIFA <-- Farmalogg: Bivirkninger, interaksjoner, trinnpris,\nbyttegruppe med legemiddeldetaljer
DIFA -> DIFA: Bruk historikk til å generere varsler
Apotektekniker <-- DIFA: Reseptliste med alternativer,\nbivirkninger, varsler
deactivate DIFA

group Utføres av Apotektekniker etter behov
Apotektekniker -> DIFA: Beregne refusjon basert på varevalg
Apotektekniker -> DIFA: Forfalskningskontroll
Apotektekniker -> DIFA: Verifiser utlevering
end group

group Kan skje på andre tidspunkt
Farmasøyt -> DIFA: Hent resepter klar til farmasøytkontroll
Farmasøyt -> DIFA: Utfør farmasøytkontroll
end group


Apotektekniker -> DIFA: Registrer utlevering med varevalg, strekkoder,\noppdatert etikett,\nfarmasøyts aksjon for alle varsler,\nunderskrift
activate DIFA
DIFA -> DIFA: Verifiser rekvirent, varsler, strekkoder
DIFA -> RF: Utleveringsmelding
DIFA -> HELFO: Send refusjonskrav
Apotektekniker <-- DIFA: OK/feilkoder
deactivate DIFA

@enduml
