@startuml

participant POS
box "DIFA tjenesten"
    participant DIFA
    database HPR
    database Farmalogg
end box
database Personregisteret
database RF
participant HELFO

activate DIFA
POS -> DIFA: Find person basert på kriterier
DIFA -> Personregisteret
POS <-- DIFA: Liste med personer
deactivate DIFA

POS -> DIFA: Registrer papir resept på legemiddel, pasient, rekvirent
activate DIFA
DIFA -> HPR: Hent rekvisisjonsrett for forskriver
DIFA -> RF: Hent resepter for person
DIFA <-- RF: Reseptliste (historisk)
DIFA -> Farmalogg: Medikament-informasjon
DIFA <-- Farmalogg: Bivirkninger, interaksjoner, trinnpris,\nbyttegruppe med legemiddeldetaljer
DIFA -> DIFA: Bruk historikk til å generere varsler
POS <-- DIFA: Reseptliste med alternativer,\nbivirkninger, varsler
deactivate DIFA

group Utføres av POS etter behov
POS -> DIFA: Beregne refusjon basert på varevalg
POS -> DIFA: Forfalskningskontroll
end group


POS -> DIFA: Registrer utlevering med varevalg, strekkoder,\noppdatert etikett,\nfarmasøyts aksjon for alle varsler,\nunderskrift, scannet dokumentasjon
Note right of POS: Her kunne DIFA tilby en mobil app for farmasøyt for farmasøytkontroll
activate DIFA
DIFA -> DIFA: Verifiser rekvirent, varsler, strekkoder
DIFA -> RF: Utleveringsmelding
DIFA -> HELFO: Send refusjonskrav
POS <-- DIFA: OK/feilkoder
deactivate DIFA


@enduml
