@startuml

title DIFA i testmodus uten kjedetilkobling (test)

actor Apotektekniker
actor Farmasøyt
box "Kjede"
    participant POS #silver
    participant Varesystem #silver
end box
box "DIFA"
    participant DifaGUI
    participant DIFA
end box

Apotektekniker -> POS: Velger hent resept
Apotektekniker <-- POS: Redirect
group Dialog med DIFA
Apotektekniker -> DifaGUI: Vis Personsøk skjema
Apotektekniker -> DifaGUI: Angi person (fødselsnummer eller navn + fødselsdato)
Apotektekniker <-- DifaGUI: Vis resepter
Apotektekniker -> DifaGUI: Velg resept
activate DifaGUI
DifaGUI-> DIFA: Hent resept 
DIFA -> DIFA: Hent varer i byttegruppe
DIFA -> DIFA: Påfør informasjon og varsler
DifaGUI <-- DIFA
note over Varesystem : Brukerens kjede har ikke integrasjon fra DIFA GUI
DifaGUI-> Varesystem: <strike>Pris og beholdning
Apotektekniker <--DifaGUI: <color red>Varsler, byttealternativer <b>uten</b> priser, beholdning
deactivate DifaGUI
Apotektekniker -> DifaGUI: <color red>Velg legemiddel, <b>angi pris

newpage

Apotektekniker <-- DifaGUI: Klargjør reseptetikett, ta opp print-dialog
note right of Apotektekniker: DIFA GUI åpner nettlesers print-dialog
Apotektekniker -> Apotektekniker: Skriv reseptetikett
Apotektekniker -> DifaGUI: Skriver inn GTIN og etikettnummer
note right of Apotektekniker: Eller strekkodescanner i tastaturmodus
DifaGUI -> DIFA: Teknisk kontroll
Apotektekniker -> Farmasøyt: "Kan du gjøre\nfarmasøytkontroll"
Farmasøyt -> DifaGUI: Vis resepter klar til farmasøytkontroll
Farmasøyt -> DifaGUI: Utfør farmasøytkontroll
Apotektekniker <- Farmasøyt: "Vær så god"
Apotektekniker -> DifaGUI: Utlever
activate DifaGUI
note over Varesystem : Brukerens kjede har ikke integrasjon fra DIFA GUI
DifaGUI -> POS: <strike>Sett reseptkurv i kasse (erstatte)
Apotektekniker <-- DifaGUI: Vis signaturpad
deactivate DifaGUI
note right of Apotektekniker: Last opp fil fra signatur pad eller bruk f.eks.\nhttps://github.com/szimek/signature_pad
Apotektekniker -> DifaGUI: <color red>Registrer pasient signatur og bekreft betaling
activate DifaGUI
DifaGUI -> DIFA: <color red>Fullfør utlevering
Apotektekniker <-- DifaGUI
deactivate DifaGUI

@enduml
