@startuml

actor Apotekansatt
actor Farmasøyt
box "DIFA tjenesten"
    participant DIFA
    database HPR
    database Farmalogg
end box
database Personregisteret
database RF
participant HELFO

activate DIFA
Apotekansatt -> DIFA: Find person basert på kriterier
DIFA -> Personregisteret
Apotekansatt <-- DIFA: Liste med personer
deactivate DIFA

Apotekansatt -> DIFA: Hent resepter for person
activate DIFA
DIFA -> RF: Hent resepter for person
Apotekansatt <-- DIFA: Reseptliste
deactivate DIFA

Apotekansatt -> DIFA: Ekspeder resept
activate DIFA
DIFA -> RF: Ekspeder resept
DIFA -> HPR: Hent rekvisisjonsrett
DIFA -> Farmalogg: Medikament-informasjon
DIFA <-- Farmalogg: Bivirkninger, interaksjoner, trinnpris,\nbyttegruppe med legemiddeldetaljer
DIFA -> DIFA: Bruk historikk til å generere varsler
Apotekansatt <-- DIFA: Reseptliste med alternativer,\nbivirkninger, varsler
deactivate DIFA

group Utføres av Apotekansatt etter behov
Apotekansatt -> DIFA: Beregne refusjon basert på varevalg
Apotekansatt -> DIFA: Forfalskningskontroll
Apotekansatt -> DIFA: Verifiser utlevering
end group

group Kan skje på andre tidspunkt
Farmasøyt -> DIFA: Hent resepter klar til farmasøytkontroll
Farmasøyt -> DIFA: Utfør farmasøytkontroll
end group


Apotekansatt -> DIFA: Registrer utlevering med varevalg, strekkoder,\noppdatert etikett,\nfarmasøyts aksjon for alle varsler,\nunderskrift
activate DIFA
DIFA -> DIFA: Verifiser rekvirent, varsler, strekkoder
DIFA -> RF: Utleveringsmelding
DIFA -> HELFO: Send refusjonskrav
Apotekansatt <-- DIFA: OK/feilkoder
deactivate DIFA

@enduml
