@startuml

title DIFA i testmodus uten kjedetilkobling (test)

actor Apotekansatt
actor Farmasøyt
box "Kjede"
    participant POS #silver
    participant Varesystem #silver
end box
box "DIFA"
    participant DifaGUI
    participant DIFA
end box

Apotekansatt -> POS: Velger hent resept
Apotekansatt <-- POS: Redirect
group Dialog med DIFA
Apotekansatt -> DifaGUI: Vis Personsøk skjema
Apotekansatt -> DifaGUI: Angi person (fødselsnummer eller navn + fødselsdato)
Apotekansatt <-- DifaGUI: Vis resepter
Apotekansatt -> DifaGUI: Velg resept
activate DifaGUI
DifaGUI-> DIFA: Hent resept 
DIFA -> DIFA: Hent varer i byttegruppe
DIFA -> DIFA: Påfør informasjon og varsler
DifaGUI <-- DIFA
note over Varesystem : Brukerens kjede har ikke integrasjon fra DIFA GUI
DifaGUI-> Varesystem: <strike>Pris og beholdning
Apotekansatt <--DifaGUI: <color red>Varsler, byttealternativer <b>uten</b> priser, beholdning
deactivate DifaGUI
Apotekansatt -> DifaGUI: <color red>Velg legemiddel, <b>angi pris

newpage

Apotekansatt <-- DifaGUI: Klargjør reseptetikett, ta opp print-dialog
note right of Apotekansatt: DIFA GUI åpner nettlesers print-dialog
Apotekansatt -> Apotekansatt: Skriv reseptetikett
Apotekansatt -> DifaGUI: Skriver inn GTIN og etikettnummer
note right of Apotekansatt: Eller strekkodescanner i tastaturmodus
DifaGUI -> DIFA: Teknisk kontroll
Apotekansatt -> Farmasøyt: "Kan du gjøre\nfarmasøytkontroll"
Farmasøyt -> DifaGUI: Vis resepter klar til farmasøytkontroll
Farmasøyt -> DifaGUI: Utfør farmasøytkontroll
Apotekansatt <- Farmasøyt: "Vær så god"
Apotekansatt -> DifaGUI: Utlever
activate DifaGUI
note over Varesystem : Brukerens kjede har ikke integrasjon fra DIFA GUI
DifaGUI -> POS: <strike>Sett reseptkurv i kasse (erstatte)
Apotekansatt <-- DifaGUI: Vis signaturpad
deactivate DifaGUI
note right of Apotekansatt: Last opp fil fra signatur pad eller bruk f.eks.\nhttps://github.com/szimek/signature_pad
Apotekansatt -> DifaGUI: <color red>Registrer pasient signatur og bekreft betaling
activate DifaGUI
DifaGUI -> DIFA: <color red>Fullfør utlevering
Apotekansatt <-- DifaGUI
deactivate DifaGUI

@enduml
