@startuml

title Inhalasjonsveiledning

actor Farmasøyt
participant Kjedesystem
participant Difa
participant HELFO

group Dialog med Kjede Kjedesystem
Farmasøyt -> Kjedesystem: Velger Inhalasjonsveiledning
Farmasøyt <-- Kjedesystem: Redirect
end group
group Dialog med Difa
Farmasøyt -> Difa: Vis Personsøk skjema
Farmasøyt -> Difa: Angi person (fødselsnummer eller navn + fødselsdato)
Farmasøyt <-- Difa: Vis instrukser for behandlingen
Farmasøyt -> Difa: Angi informasjon om behandlingen (eks: antall repetisjoner)
Farmasøyt -> Difa: Fullfør behandling
activate Difa
Difa -> Difa: Journalføre behandling
Difa -> Difa: Beregne refusjon og egenandel
Difa -> HELFO: Refusjonskrav
Farmasøyt <-- Difa: Redirect med varenummer og egenandel
deactivate Difa
end group
group Dialog med Kjede Kjedesystem
Farmasøyt -> Kjedesystem: Legg til egenandel i handlekurv
Farmasøyt <-> Kjedesystem: Vis oppgjørsgrunnlag
Farmasøyt <-> Kjedesystem: Fullfør salg
end group

@enduml