@startuml

title Difa leser fra kjedenes varesystem (opsjon)

actor Apotektekniker
actor Farmasøyt
box "Kjede"
    participant POS
    participant Varesystem
end box
box " Difa"
  participant DifaGUI
participant Difa
end box

Apotektekniker -> POS: Velger hent resept
Apotektekniker <-- POS: Redirect
group Dialog med Difa
Apotektekniker -> DifaGUI: Vis Personsøk skjema
Apotektekniker -> DifaGUI: Angi person (fødselsnummer eller navn + fødselsdato)
Apotektekniker <-- DifaGUI: Vis resepter
Apotektekniker -> DifaGUI: Velg resept
activate DifaGUI
DifaGUI-> Difa: Hent resept 
Difa -> Difa: Hent varer i byttegruppe
Difa -> Difa: Påfør informasjon og varsler
DifaGUI <-- Difa
note over Varesystem : Kjeden har ansvar for at varesystem\nimplementere API spesfisert av Difa
DifaGUI-> Varesystem: <color red>Pris og beholdning for\n<color red>alle aktuelle legemidler\n<color red>for apotek
DifaGUI<-- Varesystem
Apotektekniker <--DifaGUI: Varsler, byttealternativer med priser, beholdning
deactivate DifaGUI
Apotektekniker -> DifaGUI: Velg legemiddel
Apotektekniker <-- DifaGUI: Klargjør reseptetikett, ta opp print-dialog

newpage

note right of Apotektekniker: Difa GUI åpner nettlesers print-dialog
Apotektekniker -> Apotektekniker: Skriv reseptetikett
Apotektekniker -> DifaGUI: Scan strekkode på etikett og pakning
note right of Apotektekniker: Strekkodescanner i tastaturmodus
DifaGUI -> Difa: Teknisk kontroll
Apotektekniker -> Farmasøyt: "Kan du gjøre\nfarmasøytkontroll"
Farmasøyt -> DifaGUI: Vis resepter klar til farmasøytkontroll
Farmasøyt -> DifaGUI: Utfør farmasøytkontroll
Apotektekniker <- Farmasøyt: "Vær så god"
Apotektekniker -> DifaGUI: Utlever
Apotektekniker -> POS: Importer reseptkurver
activate POS
POS -> Difa: <color red>List reseptkurver tilhørende apotekteknikeren
Apotektekniker <-- POS: Reseptkurvliste
deactivate POS
Apotektekniker -> POS: Plukk en eller flere reseptkurver
activate POS
POS -> Difa: <color red>Hent reseptkurv
Apotektekniker <-- POS: Vis oppdatert "handlekurv"
deactivate POS
Apotektekniker -> POS: <color red>Registrer signatur og betaling
activate POS
POS -> Difa: <color red>Fullfør utlevering
Apotektekniker <-- POS
deactivate POS

@enduml
