@startuml

title DIFA leser fra kjedenes varesystem (opsjon)

actor Apotektekniker
actor Farmasøyt
box "Kjede"
    participant POS
    participant Varesystem
end box
box "DIFA"
    participant DifaGUI
    participant DIFA
end box

Apotektekniker -> POS: Velger hent resept
Apotektekniker <-- POS: Redirect
group Dialog med DIFA
Apotektekniker -> DifaGUI: Vis Personsøk skjema
Apotektekniker -> DifaGUI: Angi person (fødselsnummer eller navn + fødselsdato)
Apotektekniker <-- DifaGUI: Vis resepter
Apotektekniker -> DifaGUI: Velg resept
activate DifaGUI
DifaGUI-> DIFA: Hent resept 
DIFA -> DIFA: Hent varer i byttegruppe
DIFA -> DIFA: Påfør informasjon og varsler
DifaGUI <-- DIFA
note over Varesystem : Kjeden har ansvar for at varesystem\nimplementere API spesfisert av DIFA
DifaGUI-> Varesystem: <color red>Pris og beholdning for\n<color red>alle aktuelle legemidler\n<color red>for apotek
DifaGUI<-- Varesystem
Apotektekniker <--DifaGUI: Varsler, byttealternativer med priser, beholdning
deactivate DifaGUI
Apotektekniker -> DifaGUI: Velg legemiddel
Apotektekniker <-- DifaGUI: Klargjør reseptetikett, ta opp print-dialog

newpage

note right of Apotektekniker: DIFA GUI åpner nettlesers print-dialog
Apotektekniker -> Apotektekniker: Skriv reseptetikett
Apotektekniker -> DifaGUI: Scan strekkode på etikett og pakning
note right of Apotektekniker: Strekkodescanner i tastaturmodus
DifaGUI -> DIFA: Teknisk kontroll
Apotektekniker -> Farmasøyt: "Kan du gjøre\nfarmasøytkontroll"
Farmasøyt -> DifaGUI: Vis resepter klar til farmasøytkontroll
Farmasøyt -> DifaGUI: Utfør farmasøytkontroll
Apotektekniker <- Farmasøyt: "Vær så god"
Apotektekniker -> DifaGUI: Utlever
Apotektekniker -> POS: Importer reseptkurver
activate POS
POS -> DIFA: <color red>List reseptkurver tilhørende apotekteknikeren
Apotektekniker <-- POS: Reseptkurvliste
deactivate POS
Apotektekniker -> POS: Plukk en eller flere reseptkurver
activate POS
POS -> DIFA: <color red>Hent reseptkurv
Apotektekniker <-- POS: Vis oppdatert "handlekurv"
deactivate POS
Apotektekniker -> POS: <color red>Registrer signatur og betaling
activate POS
POS -> DIFA: <color red>Fullfør utlevering
Apotektekniker <-- POS
deactivate POS

@enduml
