@startuml

actor Pasient
actor Farmasøyt

node DifaGUI #limegreen

package Kjedesystemer {
    node POS #lime
    node Regnskap #lime
}

node Difa #limegreen

node helsenorge.no #yellow
node HELFO #yellow
node HPR #yellow

Pasient <-> Farmasøyt
Farmasøyt -down-> DifaGUI

DifaGUI -down-> Difa
Farmasøyt -down-> POS: Alternativ
POS -down-> Difa
Regnskap -down-> Difa: Refusjonstatus

Difa -down-> helsenorge.no: Journal
Difa -down-> HELFO: Refusjon
Difa -down-> HPR: Autorisasjon

@enduml
