@startuml

participant POS
box "Difa tjenesten"
    participant Difa
    database HPR
    database Farmalogg
end box
database Personregisteret
database RF
participant HELFO

activate Difa
POS -> Difa: Find person basert på kriterier
Difa -> Personregisteret
POS <-- Difa: Liste med personer
deactivate Difa

POS -> Difa: Registrer papir resept på legemiddel, pasient, rekvirent
activate Difa
Difa -> HPR: Hent rekvisisjonsrett for forskriver
Difa -> RF: Hent resepter for person
Difa <-- RF: Reseptliste (historisk)
Difa -> Farmalogg: Medikament-informasjon
Difa <-- Farmalogg: Bivirkninger, interaksjoner, trinnpris,\nbyttegruppe med legemiddeldetaljer
Difa -> Difa: Bruk historikk til å generere varsler
POS <-- Difa: Reseptliste med alternativer,\nbivirkninger, varsler
deactivate Difa

group Utføres av POS etter behov
POS -> Difa: Beregne refusjon basert på varevalg
POS -> Difa: Forfalskningskontroll
end group


POS -> Difa: Registrer utlevering med varevalg, strekkoder,\noppdatert etikett,\nfarmasøyts aksjon for alle varsler,\nunderskrift, scannet dokumentasjon
Note right of POS: Her kunne Difa tilby en mobil app for farmasøyt for farmasøytkontroll
activate Difa
Difa -> Difa: Verifiser rekvirent, varsler, strekkoder
Difa -> RF: Utleveringsmelding
Difa -> HELFO: Send refusjonskrav
POS <-- Difa: OK/feilkoder
deactivate Difa


@enduml
