@startuml

class Patient

class MedicationOrderList

class MedicationOrder {
    productName OR
    packagingId OR
    atc + dosage
}

class MedicationOrderIssuance {
    dateWritten
    copayPeriods
}

class MedicationOrderWarning {
    interactionWarning
    newMedication
    changedDosage
    highDosage
    doubleOrder
    polypharmacy
}

class Medication

class Practitioner {
    hpr
}

class DispenseOrder {
}

class MedicationDispense {
    quantity
    scannedPackaging
    scannedLabel    
}

class MedicationDispenseAction {
    conferedWithDoctor: practitioner
    informedPatient : y/n
    notes
}

Patient -down- MedicationOrderList
MedicationOrderList -right- "*" MedicationOrder
MedicationOrder -up- MedicationOrderIssuance
MedicationOrderIssuance -up- Practitioner
MedicationOrder -down- MedicationOrderWarning
MedicationOrder -right- MedicationDispense
MedicationDispense -down- MedicationDispenseAction
MedicationOrderWarning -right- MedicationDispenseAction

MedicationOrder -up- "*" Medication: alternatives
MedicationDispense -up- Medication
DispenseOrder -up- Practitioner
DispenseOrder -down- "*" MedicationDispense

hide empty members
hide methods
@enduml
