@startuml

package Legemiddel {
    class Legemiddel {
        produktnavn
        produsent
    }

    class Virkestoff

    class VirkestoffMedStyrke {
        mengde
        enhet: mg/ml, mg/tablett
    }

    class Legemiddelstyrke {
        mengde
        enhet : mg/ml, mg/tablett
    }

    class Legemiddelform {
        
    }

    class Legemiddelpakning {
        produktID
        mengde
        enhet : antall, gram, ml
    }

    class Byttegruppe

    VirkestoffMedStyrke "*" -up-> Virkestoff
    Legemiddel "*" -up- "1..*" VirkestoffMedStyrke
    Legemiddelform "1..*" -up- Legemiddel
    Legemiddelstyrke "1..*" - Legemiddelform
    Legemiddelstyrke -up- VirkestoffMedStyrke
    Legemiddelpakning "1..*" -up- Legemiddelstyrke
    Legemiddelpakning "1.*" - "0..1" Byttegruppe    
}

class Resept

Resept -right-> VirkestoffMedStyrke
Resept -right-> Legemiddelstyrke
Resept -right-> Legemiddelpakning



hide empty members
hide methods
@enduml
