@startuml

package Medication {
    ' Legemiddel
    class Medication {
        productName
        producer
    }

    ' Virkestoff
    class Substance

    ' VirkestoffMedStyrke
    class SubstanceConcentration {
        amount
        unit: mg/ml, mg/tablet
    }

    ' Legemiddel
    class MedicationConcentration {
        amount
        unit : mg/ml, mg/tablet
    }

    ' Legemiddelform
    class MedicationForm {
        
    }

    ' Legemiddelpakning
    class MedicationPackaging {
        productIdentifier
        amount
        unit : count, grams, ml
    }

    ' Byttegruppe
    class SubstitutionGroup

    SubstanceConcentration "*" -up-> Substance
    Medication "*" -up- "1..*" SubstanceConcentration
    MedicationForm "1..*" -up- Medication
    MedicationConcentration "1..*" - MedicationForm
    MedicationConcentration -up- SubstanceConcentration
    MedicationPackaging "1..*" -up- MedicationConcentration
    MedicationPackaging "1.*" - "0..1" SubstitutionGroup    
}

' Resept
class MedicationOrder

MedicationOrder -right-> SubstanceConcentration
MedicationOrder -right-> MedicationConcentration
MedicationOrder -right-> MedicationPackaging



hide empty members
hide methods
@enduml
