@startuml

package Bransjeløsning {

skinparam component {
BorderColor black
ArrowColor black
}


    node Autorisasjonslag {
        component DIFA {
            component FullførEkspedering #8ccbdb
            component ValiderUtlevering #8ccbdb
            component Pakningskontroll #8ccbdb
            component Farmasøytkontroll #8ccbdb
            component Forskriverkontroll #8ccbdb
            component Refusjonshjemmelkontroll #8ccbdb
            component Refusjonsberegning #8ccbdb
            
            FullførEkspedering ..> ValiderUtlevering
            ValiderUtlevering ..> Pakningskontroll
            ValiderUtlevering ..> Farmasøytkontroll
            ValiderUtlevering ..> Forskriverkontroll
            ValiderUtlevering ..> Refusjonshjemmelkontroll
            ValiderUtlevering ..> Refusjonsberegning

            () "API" as API_FullførEkspedering #ececec
            API_FullførEkspedering -down- FullførEkspedering
            () "API" as API_ValiderUtlevering #ececec
            API_ValiderUtlevering -down- ValiderUtlevering

            () "API" as API_Pakningskontroll #ececec
            API_Pakningskontroll -down- Pakningskontroll
            () "API" as API_Farmasøytkontroll #ececec
            API_Farmasøytkontroll -down- Farmasøytkontroll
            () "API" as API_Forskriverkontroll #ececec
            API_Forskriverkontroll -down- Forskriverkontroll
            () "API" as API_Refusjonshjemmelkontroll #ececec
            API_Refusjonshjemmelkontroll -down- Refusjonshjemmelkontroll
            () "API" as API_Refusjonsberegning #ececec
            API_Refusjonsberegning -down- Refusjonsberegning
        }
    }

    database Resepthistorikk #8ccbdb
    database HPR #e8baa0
    database Legemidler #e8baa0
    database Regelverk #e8baa0

    FullførEkspedering -> Resepthistorikk
    Farmasøytkontroll -> Resepthistorikk
    Farmasøytkontroll -> Legemidler
    Forskriverkontroll -> HPR
    Refusjonshjemmelkontroll -> Regelverk
}

() "API" as Vei_inn #ececec
Vei_inn -down- DIFA

node Forfalskningsregisteret #e8baa0
Pakningskontroll ..> Forfalskningsregisteret

node Reseptformideleren #e8baa0
FullførEkspedering ..> Reseptformideleren


@enduml
