@startuml

title Tilgangslogg

actor Bruker1
actor Bruker2
participant POS
box "DIFA"
participant DIFA
database Innsynslogg
end box
actor Revisor

Bruker1 -> POS: Ekspeder resept
POS -> DIFA
DIFA -> Innsynslogg
Bruker1 <-- POS
Bruker1 -> POS: Vis historikk
POS -> DIFA
DIFA -> Innsynslogg
Bruker1 <-- POS
Bruker1 -> POS: Vis historikk
POS -> DIFA
DIFA -> Innsynslogg
Bruker2 <-- POS
Revisor -> Innsynslogg: Aktivitet utført av helsepersonell
Revisor <-- Innsynslogg
Revisor -> Innsynslogg: Aktivitet utført mot pasient
Revisor <-- Innsynslogg

@enduml
