@startuml

title Kjede POS bruker DIFA API

actor Apotekansatt
actor Farmasøyt
box "Kjede"
    participant POS
    participant Varesystem
    participant Reseptur
end box
box "DIFA"
    participant DIFA
    database DB
end box
participant eHelse

Apotekansatt -> POS: Velger hent resept
Apotekansatt <-- POS: Redirect
group Dialog med DIFA
Apotekansatt -> Reseptur: Vis Personsøk skjema
Apotekansatt -> Reseptur ++: Angi person (fødselsnummer eller navn + fødselsdato)
Reseptur -> DIFA: Hent reseptliste
DIFA -> eHelse: M9.1
DIFA <-- eHelse: M9.2
DIFA -> DIFA: Påfør informasjon og varsler
Reseptur <-- DIFA: Reseptliste med interaksjonsvarsler
Apotekansatt <-- Reseptur --: Vis resepter
Apotekansatt -> Reseptur ++: Ekspeder resept
Reseptur-> DIFA: Hent resept 
DIFA -> eHelse: M9.3
DIFA <-- eHelse: M9.4
DIFA -> DIFA: Påfør informasjon og varsler
DIFA -> DIFA: Hent varer i byttegruppe
DIFA -> DB: Lagre resept under ekspedering
Reseptur <-- DIFA
Reseptur-> Varesystem: Pris og beholdning for\nalle aktuelle legemidler\nfor apotek
Reseptur<-- Varesystem
Apotekansatt <--Reseptur --: Varsler, byttealternativer med priser, beholdning
Apotekansatt -> Reseptur ++: Velg legemiddel
Reseptur -> DIFA: Oppdater vare
note over Reseptur: Her vil også intervensjoner registreres
DIFA -> DIFA: Beregne refusjon
DIFA -> DB
Reseptur <-- DIFA: Oppdatert refusjon, egenandel, mellomlegg
Apotekansatt <-- Reseptur --: Vis oppdatert pris
newpage
Apotekansatt -> Reseptur ++: Oppdater reseptetikett
Reseptur -> DIFA: Oppdatert reseptetikett
DIFA -> DB
Reseptur <-- DIFA: Oppdatert reseptetikett
Apotekansatt <-- Reseptur --
Apotekansatt -> Reseptur: Skriv reseptetikett
Apotekansatt -> Reseptur: Scan strekkode på etikett og pakning
Reseptur -> DIFA: Teknisk kontroll
Apotekansatt -> Farmasøyt: "Kan du gjøre\nfarmasøytkontroll"
Farmasøyt -> DIFA: Hent resepter klar til farmasøytkontroll
DIFA -> DB
Farmasøyt -> DIFA: Utfør farmasøytkontroll
DIFA -> DB
Apotekansatt <- Farmasøyt: "Vær så god"
Apotekansatt -> Reseptur ++: Start utlevering
Reseptur -> DIFA: Valider reseptekspedering
Reseptur -> POS: Sett reseptkurv i kasse
Apotekansatt <-- Reseptur --
Apotekansatt -> POS ++: Registrer signatur og betaling
POS -> Reseptur ++: Fullfør utlevering
Reseptur -> DIFA: Fullfør utlevering
DIFA -> DB
DIFA -> eHelse: M10
DIFA -> eHelse: M18
Reseptur <-- DIFA
POS <-- Reseptur --
Apotekansatt <-- POS --

@enduml
