@startuml

title Versjon 0.2: Farmasøytiske tjenester

actor Pasient
actor Farmasøyt

node DifaGUI #limegreen

note bottom of DifaGUI: Mellomløsning slik at alle\nblir med fra starten

package Kjedesystem {
    node POS as "Ekspedering" #lime
    node Regnskap #lime
}

package Bransjesystem {
    node DIFA #limegreen
    database Journal #limegreen
    DIFA -> Journal
}

node HELFO #pink
node HPR #yellow

Pasient <-> Farmasøyt
Farmasøyt -down-> DifaGUI

DifaGUI -down-> DIFA: Alternativ
DifaGUI -down-> Journal
Farmasøyt -down-> POS
POS -down-> DIFA
Regnskap -down-> DIFA: Refusjonstatus

DIFA -down-> HELFO: Refusjon
DIFA -down-> HPR: Autorisasjon

@enduml
