@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

actor ApotekA as "Brukersystem A" #ececec
actor ApotekB as "Brukersystem B" #ececec

node Ekspedering #8ccbdb
node ERP #8ccbdb
node DIFA #5bb6cc
node RF #e8cad8
node Farmalogg #c7395b
node SLV #c7395b
node HELFO #e8cad8
node Nettapotek #8ccbdb
node Multidose #8ccbdb
node FarmaPro <<bro>> #e8cad8

ApotekA -down-> Ekspedering
Ekspedering -down-> DIFA
Ekspedering -left-> ERP
Nettapotek -down-> DIFA
Multidose -down-> DIFA
ApotekB -down-> FarmaPro
FarmaPro -down-> DIFA
DIFA <-left-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
DIFA <-right- Farmalogg
Farmalogg <-down- SLV: FEST
DIFA <-down-> HELFO: M18, M22, M23


@enduml
