@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

actor Pasient #ececec
actor Apotekansatt #ececec

node DifaGUI #319aad

package Apoteksystem {
    node POS as "Brukersystem" #8ccbdb
    node Regnskap #8ccbdb
}

package Bransjesystem {
    node DIFA #319aad
    database Journal #319aad
    DIFA -> Journal
}

node HELFO #e8cad8
node HPR #c7395b

Pasient <-> Apotekansatt
Apotekansatt -down-> DifaGUI

DifaGUI -down-> DIFA: Alternativ
DifaGUI -down-> Journal
Apotekansatt -down-> POS
POS -down-> DIFA
Regnskap -down-> DIFA: Refusjonstatus

DIFA -down-> HELFO: Refusjon
DIFA -down-> HPR: Autorisasjon

@enduml
