@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

actor Pasient #ececec
actor Apotekansatt #ececec
actor Farmasøyt #ececec
actor Lege #ececec

package Kjede {
    node Brukersystem #8ccbdb
    node ERP #8ccbdb
}

node DifaGUI #319aad
node DIFA #319aad

node RF #e8cad8
node Farmalogg #c7395b
node EPJ #c7395b
node HELFO #e8cad8
node SLV #c7395b
node HDIR #c7395b


Pasient <-down-> Lege
Lege -right-> EPJ: Resept
EPJ -right-> RF: Resept
Pasient <-right-> Apotekansatt
Apotekansatt -down-> DifaGUI: Ekspeder
Apotekansatt -down-> Brukersystem: Motta betaling
Farmasøyt -down-> DifaGUI: Farmasøytkontroll

DIFA <-left-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
DIFA <-down-> HELFO: M18, M22, M23
DIFA <-down- HDIR: HPR db

Farmalogg <-down- SLV: FEST
DifaGUI -down-> DIFA
DifaGUI -down-> ERP: Priser og beholdning
ERP <-left- Brukersystem
Brukersystem -down-> DIFA: Reseptkurv, utlever
DIFA <-right- Farmalogg


@enduml
