@startuml

title Applikasjonsarkitektur

node VMWare {
    node OpenShift {
        node HAProxy  #319aad
    
        node Docker {
            node JVM {
                node Jetty {
                    component AccessControl #319aad
                    component Controller #319aad
                    component Action #319aad
                    component Service #319aad
                    component "Gateway" as RFGateway #319aad
                    component "Gateway" as HELFOGateway #319aad
                    component "Gateway" as MailGateway #319aad
                    component "Repository" as ApotekRepository #319aad
                    component "Repository" as PasientRepository #319aad
                    
                    () servlet  #319aad
                    servlet -down- Controller
                    
                    Controller - "*" Action
                    Action -down- Service
                    Service -down- ApotekRepository
                    Service -down- PasientRepository
                    Service -- RFGateway
                    Service -- HELFOGateway
                    Service -- MailGateway
                    
                    AccessControl .left.> servlet
                }
                Jetty ..> servlet
            }
        }
        () "https" as jettyhttps #319aad
        jettyhttps -down- Jetty
        
        HAProxy .down.> jettyhttps
    }
}
() https #319aad
https -down- HAProxy

node "PostgreSQL VMWare" {
    node PostgreSQL {
        database Apotek  #319aad
        database Pasient  #319aad
        database "..." as db  #319aad
    }
}
() "SQL" as ApotekSQL
ApotekSQL - Apotek

() "SQL" as PasientSQL
PasientSQL - Pasient

ApotekRepository .down.> ApotekSQL
PasientRepository .down.> PasientSQL

cloud "Eksterne tjenester" {
    node Reseptformidleren #e8cad8
    node HELFO #e8cad8
    node Mailserver #c7395b
}

RFGateway -right- Reseptformidleren
HELFOGateway -right- HELFO
MailGateway -right- Mailserver

@enduml