@startuml

title Inhalasjonsveiledning

actor Apotekansatt
participant POS
participant DIFA
participant HELFO


group Dialog med Kjede POS
Apotekansatt -> POS: Velger Inhalasjonsveiledning
Apotekansatt <-- POS: Redirect
end group
group Dialog med DIFA
Apotekansatt -> DIFA: Vis Personsøk skjema
Apotekansatt -> DIFA: Angi person (fødselsnummer eller navn + fødselsdato)
Apotekansatt <-- DIFA: Vis instrukser for behandlingen
Apotekansatt -> DIFA: Angi informasjon om behandlingen (eks: antall repetisjoner)
Apotekansatt -> DIFA: Fullfør behandling
activate DIFA
DIFA -> DIFA: Journalføre behandling
DIFA -> DIFA: Beregne refusjon og egenandel
DIFA -> HELFO: Refusjonskrav
Apotekansatt <-- DIFA: Redirect med varenummer og egenandel
deactivate DIFA
end group
group Dialog med Kjede POS
Apotekansatt -> POS: Legg til egenandel i handlekurv
Apotekansatt <-> POS: Vis oppgjørsgrunnlag
Apotekansatt <-> POS: Fullfør salg
end group


