@startuml

box "Kjede"
    participant POS
    participant Økonomisystem
end box

box "DIFA"
    participant "DIFA"
end box

participant HELFO

POS -> DIFA: Register utlevering med strekkoder
activate DIFA
...
DIFA -> HELFO: Send refusjonskrav (M18)
POS <-- DIFA: OK/feilkoder
deactivate DIFA
POS -> Økonomisystem: Registrer fordring

== Økonomisystem holder seg periodisk oppdatert med status på fordringer ==
Økonomisystem -> DIFA: Status på fordringer
Økonomisystem <-- DIFA: Ikke bekreftet
...
HELFO -> DIFA: Oppgjørsresultat (M22)
Økonomisystem -> DIFA: Status på fordringer
Økonomisystem <-- DIFA: Bekreftet
...
HELFO -> DIFA: Utbetalingsmelding (M23)
Økonomisystem -> DIFA: Status på fordringer
Økonomisystem <-- DIFA: Betalt
...

@enduml
