@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

actor Tester #ececec

package Demo {
    node DemoPOS as "Ekspedering" #319aad
}

package Apoteksystem {
    node POS as "Brukersystem" #8ccbdb
    node ERP #ececec
}

node DIFA #319aad

package "Datasett som tilrettelegger testing" {
    node RF #e8cad8
    node HELFO #e8cad8
    node FMD #e8cad8
}

Tester -right-> RF: Resept
Tester -down-> POS

DemoPOS -down-> DIFA: DIFA API
POS -down-> DIFA: DIFA API
POS -left-> ERP
DIFA <-down-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
DIFA <-down-> HELFO: M18, M22, M23


@enduml
