@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0


actor Pasient
actor Apotekansatt
actor Farmasøyt
actor Lege
node EPJ

package Apoteksystemer {
    node POS as "Brukersystemer" #8ccbdb
    node ERP #8ccbdb
    node Nettapotek #8ccbdb
    node Multidose #8ccbdb
}
node DIFA #319aad

node RF #e8cad8
node Farmalogg #c7395b
node EPJ #c7395b
node HELFO #e8cad8
node SLV #c7395b
node HDIR #c7395b

Pasient <-down-> Lege
Lege -right-> EPJ: Resept
EPJ -right-> RF: Resept
Pasient <-right-> Apotekansatt
Apotekansatt -down-> POS
Farmasøyt -down-> POS
Farmasøyt -down-> DIFA: Farmasøytkontroll

POS -down-> DIFA
POS -left-> ERP
Nettapotek -down-> DIFA
Multidose -down-> DIFA
DIFA <-left-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
DIFA <-right- Farmalogg
Farmalogg <-down- SLV: FEST
DIFA <-down-> HELFO: M18, M22, M23
DIFA <-down- HDIR: HPR db


@enduml
