@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

node Apotek1 #c7395b
node Apotek2 #c7395b
node ApotekN #c7395b
node Kjede #c7395b
node FHI #80d3a4

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

interface FarmasøytApp <<opsjon>> #8ccbdb

cloud DIFA {
    cloud NAN as "Point of delivery" #ff8fa3
    
    node LegemiddelSync <<Java>> #8ccbdb
    node HPRSync <<Java>> #8ccbdb
    node Reseptur <<Java>> #8ccbdb
    node Resepthistorikk <<Java>> #8ccbdb
    node Farmasøytisk <<Java>> #8ccbdb

    database Legemidler <<PostgreSQL>> #8ccbdb
    database Resepter <<PostgreSQL>> #8ccbdb
    database Journal <<PostgreSQL>> #8ccbdb
    database HPR <<PostgreSQL>> #8ccbdb
    
    node KeyVault #8ccbdb

    Reseptur -down-> Resepter
    Reseptur -down-> KeyVault
    Reseptur -down-> Legemidler
    Resepthistorikk -down-> Resepter
    Farmasøytisk -down-> Journal
}

cloud DifaRapport {
    node Rapport #8ccbdb
    database RapportDB <<PostgreSQL>> #8ccbdb

    Rapport -down-> RapportDB
}

node FarmaLogg #80d3a4
LegemiddelSync <-right- FarmaLogg
LegemiddelSync -down-> Legemidler

node Helsedir #80d3a4
HPRSync <-right- Helsedir
HPRSync -down-> HPR


Resepter -right-> RapportDB: Anonymisering

cloud Internet

Apotek1 -down-> Kjede
Apotek2 -down-> Kjede
ApotekN -down-> Kjede
Kjede -down-> NAN
FarmasøytApp -down-> NAN
NAN -down-> Reseptur
NAN -down-> Resepthistorikk
NAN -down-> Farmasøytisk

Kjede -down-> Internet
FHI -down-> Internet
data.norge.no -down-> Internet
Internet -down-> Rapport

cloud NHN as "Norsk helsenett" #80d3a4

package eHelse {
    node RF #80d3a4
    node HELFO #80d3a4
    node helsenorge.no #80d3a4
}

Reseptur -> NHN
NHN -down-> eHelse
@enduml
