	@startuml

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

actor Pasient #ececec
actor Farmasøyt #ececec

node DifaGUI #319aad

note bottom of DifaGUI #ff8fa3: Mellomløsning slik at alle\nblir med fra starten

package Kjedesystem {
    node POS as "Ekspedering" #8ccbdb
    node Regnskap #8ccbdb
    node Rapportering #8ccbdb
}

package Bransjesystem {
    node DIFA #319aad
    database Journal #319aad
    DIFA -> Journal
}

package FarmaPro {
    node Meldingstjenesten #e8baa0
    node FarmaPro1 as "FarmaPro" #e8baa0
    node FarmaPro2 as "FarmaPro" #e8baa0
    node FarmaPro3 as "FarmaPro" #e8baa0
    node FarmaPro4 as "FarmaPro" #e8baa0
}

FarmaPro1 .up.> Meldingstjenesten: Nattlig migrering
FarmaPro2 .up.> Meldingstjenesten: Nattlig migrering
FarmaPro3 .up.> Meldingstjenesten: Nattlig migrering
FarmaPro4 .up.> Meldingstjenesten: Nattlig migrering

Meldingstjenesten .up.> Journal: Nattlig migrering


Pasient <-> Farmasøyt
Farmasøyt -down-> DifaGUI

DifaGUI -down-> DIFA: Alternativ
Farmasøyt -down-> POS
POS -down-> DIFA
Rapportering -down-> DIFA
Regnskap -down-> DIFA: Refusjonstatus




@enduml
