@startuml

actor Pasient
actor Apotekansatt
actor Farmasøyt
actor Lege

package Kjedesystemer {
    node POS #lime
    node ERP #lime
    node Nettapotek #lime
    node Multidose #lime
}
node DIFA #limegreen

node RF #pink
node Farmalogg #yellow
node SLV #yellow
node HELFO #pink
node HDIR #yellow
node helsenorge.no #yellow

Pasient <-down-> Lege
Lege -right-> EPJ: Resept
EPJ -right-> RF: Resept
Pasient <-right-> Apotekansatt
Apotekansatt -down-> POS
Farmasøyt -down-> POS
Farmasøyt -down-> DIFA: Farmasøytkontroll

POS -down-> DIFA
POS -left-> ERP
Nettapotek -down-> DIFA
Multidose -down-> DIFA
DIFA <-left-> RF: M9.1, M9.2,\nM9.3, M9.4,\nM10
DIFA <-right- Farmalogg
Farmalogg <-down- SLV: FEST
DIFA <-down-> HELFO: M18, M22, M23
DIFA <-down- HDIR: HPR db
DIFA -down-> helsenorge.no: Journal


@enduml
