@startuml

title Implementasjon av tjenesten Hent Resept

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

box "Apoteksystem" #ececec
    'actor Apotekansatt
    participant Kjedesystem #8ccbdb
    participant Reseptekspedering as "Resept\nekspedering" #8ccbdb
end box

box "Bransjeløsningen" #ececec
    participant Ekspedisjonsstøtte as "Ekspedisjons\nstøtte" #319aad
    participant Regelmotor <<open source>> #319aad
end box

box "Norsk Helsenett" #ececec
    database LegemiddelInfo as "Legemiddel\ninformasjon" #319aad
    database Resepthistorikk as "Resept\nhistorikk" #319aad
    participant ReseptformidlerTjeneste as "Resept\nformidleren" #ff8fa3
end box


Kjedesystem -> Reseptekspedering ++: M9.3
Reseptekspedering -> ReseptformidlerTjeneste ++: M9.3
Reseptekspedering <-- ReseptformidlerTjeneste --: M9.4,M1,M10
Reseptekspedering -> Ekspedisjonsstøtte ++: Beregn\ntilleggsinformasjon
Ekspedisjonsstøtte <-- Resepthistorikk--: Historikk
Ekspedisjonsstøtte <-- LegemiddelInfo--: Legemiddelinfo
Ekspedisjonsstøtte  -> Regelmotor++: M1, Historikk
Ekspedisjonsstøtte  <-- Regelmotor--: Faglige varsler
Ekspedisjonsstøtte  -> Regelmotor++: Etikettekst
Ekspedisjonsstøtte  <-- Regelmotor--: Beriket Etikettekst
Reseptekspedering <-- Ekspedisjonsstøtte --
Kjedesystem <-- Reseptekspedering--: "M9.4,\n historikk,\n støtte"

@enduml