@startuml

title Implementasjon av tjenesten Hent Resept

skinparam ArrowColor #b1b1b0
skinparam BorderColor #b1b1b0

box "Apoteksystem" #ececec
    'actor Apotekansatt
    participant Brukersystem #8ccbdb
end box

box "Bransjeløsningen" #ececec
    participant Reseptekspedering as "Resept-\nekspedering" #319aad
    participant Ekspedisjonsstøtte as "Ekspedisjons-\nstøtte" #319aad
    participant Regelmotor #319aad
    database LegemiddelInfo as "Legemiddel-\ninformasjon" #319aad
    database Resepthistorikk as "Resept-\nhistorikk" #319aad
    participant ReseptformidlerTjeneste as "Reseptformidler-\nTjeneste" #319aad
end box

box "Norsk Helsenett" #ececec
    participant Reseptformidleren as "Resept-\nformidleren" #ff8fa3
end box


Brukersystemsystem -> Reseptekspedering ++: M9.3 Valg av resept
Reseptekspedering -> ReseptformidlerTjeneste ++: M9.3 Valg av resept
ReseptformidlerTjeneste -> Reseptformidleren ++: M9.3 Valg av resept
ReseptformidlerTjeneste <-- Reseptformidleren --: M9.4 [+ M1] Reseptnedlastning
Reseptekspedering <-- ReseptformidlerTjeneste --: M9.4 [+ M1] Reseptnedlastning
Reseptekspedering -> Ekspedisjonsstøtte ++: Beregn\ntilleggsinformasjon [M1]
Ekspedisjonsstøtte <-- Resepthistorikk--: Historikk
Ekspedisjonsstøtte <-- LegemiddelInfo--: Legemiddelinfo
Ekspedisjonsstøtte  -> Regelmotor++: Legemiddel
Ekspedisjonsstøtte  <-- Regelmotor--: Byttevarer
Ekspedisjonsstøtte  -> Regelmotor++: M1, Historikk
Ekspedisjonsstøtte  <-- Regelmotor--: Faglige varsler
Ekspedisjonsstøtte  -> Regelmotor++: M1, Legemiddel, Etikettekst
Ekspedisjonsstøtte  <-- Regelmotor--: Beriket Etikettekst
Ekspedisjonsstøtte  -> Regelmotor++: ...
Ekspedisjonsstøtte  <-- Regelmotor--: 
Reseptekspedering <-- Ekspedisjonsstøtte --
Brukersystem <-- Reseptekspedering--: "M9.4 [+ M1],\n historikk,\n støtte"

@enduml
